import { BaseSeeder } from '@adonisjs/lucid/seeders'
import PickupPoint from '#models/pickup_point'

export default class extends BaseSeeder {
  async run() {
    // Using updateOrCreateMany is better for seeding
    // It prevents duplicate entries if you run the seeder multiple times
    await PickupPoint.updateOrCreateMany('slug', [
      {
        name: 'Point Relais KesiMarket - Douala Centre',
        slug: 'douala-centre',
        address: "123 Avenue de l'Indépendance, Douala, Cameroun",
        city: 'Douala',
        postalCode: '00237',
        phone: '+237 6 12 34 56 78',
        email: 'douala-centre@kesimarket.cm',
        hours: 'Lun-Ven: 8h-18h, Sam: 9h-17h',
        services: ['Retrait', 'Dépôt', 'Conseil'],
        latitude: 4.0511,
        longitude: 9.7679,
        rating: 4.8,
        reviewsCount: 156,
        isActive: true,
        description:
          'Notre point de relais principal à Douala, équipé pour tous vos besoins en matériel électrique.',
        managerName: 'Jean-Baptiste Mballa',
        managerPhone: '+237 6 98 76 54 32',
        managerPhoto:
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        countryCode: 'CM',
        sortOrder: 1,
      },
      {
        name: 'Point Relais KesiMarket - Yaoundé Central',
        slug: 'yaounde-central',
        address: "456 Boulevard de l'Unité, Yaoundé, Cameroun",
        city: 'Yaoundé',
        postalCode: '00238',
        phone: '+237 6 78 90 12 34',
        email: 'yaounde-central@kesimarket.cm',
        hours: 'Lun-Ven: 8h30-18h30, Sam: 9h-17h30',
        services: ['Retrait', 'Dépôt', 'Installation'],
        latitude: 3.848,
        longitude: 11.5021,
        rating: 4.6,
        reviewsCount: 89,
        isActive: true,
        description:
          "Point de relais stratégique dans la capitale, avec service d'installation disponible.",
        managerName: 'Marie-Claire Fouda',
        managerPhone: '+237 6 87 65 43 21',
        managerPhoto:
          'https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=150&h=150&fit=crop&crop=face',
        countryCode: 'CM',
        sortOrder: 2,
      },
      {
        name: 'Point Relais KesiMarket - Bafoussam',
        slug: 'bafoussam',
        address: '789 Rue du Marché, Bafoussam, Cameroun',
        city: 'Bafoussam',
        postalCode: '00239',
        phone: '+237 6 34 56 78 90',
        email: 'bafoussam@kesimarket.cm',
        hours: 'Lun-Ven: 8h-19h, Sam: 9h-18h',
        services: ['Retrait', 'Dépôt', 'Formation'],
        latitude: 5.4781,
        longitude: 10.4165,
        rating: 4.7,
        reviewsCount: 67,
        isActive: true,
        description:
          "Notre antenne dans l'Ouest du Cameroun, avec des formations techniques régulières.",
        managerName: 'Paul Kamdem',
        managerPhone: '+237 6 76 54 32 10',
        countryCode: 'CM',
        sortOrder: 3,
      },
      {
        name: 'Point Relais KesiMarket - Garoua',
        slug: 'garoua',
        address: '321 Avenue du Nord, Garoua, Cameroun',
        city: 'Garoua',
        postalCode: '00240',
        phone: '+237 6 90 12 34 56',
        email: 'garoua@kesimarket.cm',
        hours: 'Lun-Ven: 8h-18h, Sam: 9h-17h',
        services: ['Retrait', 'Dépôt', 'Conseil'],
        latitude: 9.3265,
        longitude: 13.3958,
        rating: 4.9,
        reviewsCount: 43,
        isActive: true,
        description:
          'Point de relais desservant le Grand Nord, avec une équipe experte en solutions énergétiques.',
        managerName: 'Ahmadou Bello',
        managerPhone: '+237 6 65 43 21 09',
        countryCode: 'CM',
        sortOrder: 4,
      },
      // Points de relais au Gabon
      {
        name: 'Point Relais Rexel - Libreville Port-Gentil',
        slug: 'libreville-port-gentil',
        address: '45 Boulevard Triomphal, Libreville, Gabon',
        city: 'Libreville',
        postalCode: '00241',
        phone: '+241 07 11 22 33',
        email: 'libreville@rexel-gabon.com',
        hours: 'Lun-Ven: 8h-18h, Sam: 9h-16h',
        services: ['Retrait', 'Dépôt', 'Conseil', 'Installation'],
        latitude: 0.4162,
        longitude: 9.4673,
        rating: 4.5,
        reviewsCount: 32,
        isActive: true,
        description: 'Point de relais principal au Gabon avec service installation.',
        managerName: 'Pierre Obame',
        managerPhone: '+241 07 99 88 77',
        managerPhoto:
          'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        countryCode: 'GA',
        sortOrder: 5,
      },
      // Points de relais au Congo
      {
        name: 'Point Relais Rexel - Brazzaville Centre',
        slug: 'brazzaville-centre',
        address: '12 Avenue Patrice Lumumba, Brazzaville, République du Congo',
        city: 'Brazzaville',
        postalCode: '00242',
        phone: '+242 06 123 45 67',
        email: 'brazzaville@rexel-congo.com',
        hours: 'Lun-Ven: 8h-17h30, Sam: 9h-16h',
        services: ['Retrait', 'Dépôt', 'Formation'],
        latitude: -4.2634,
        longitude: 15.2429,
        rating: 4.3,
        reviewsCount: 28,
        isActive: true,
        description: 'Notre antenne principale à Brazzaville avec formations techniques.',
        managerName: 'Sylvain Makosso',
        managerPhone: '+242 06 987 65 43',
        managerPhoto:
          'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        countryCode: 'CG',
        sortOrder: 6,
      },
    ])
  }
}
