import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Service from '#models/service'

export default class extends BaseSeeder {
  async run() {
    // Services principaux (non modifiables par l'admin)
    const services = [
      {
        name: 'Conseil et Expertise',
        slug: 'conseil',
        shortDescription:
          "Services de conseil technique et d'expertise pour vos projets électriques",
        type: 'primary' as const,
        category: 'conseil' as const,
        status: 'active' as const,
        icon: 'lightbulb',
        color: '#3B82F6',
        features: [
          'Audit technique complet',
          'Étude de faisabilité',
          'Optimisation énergétique',
          'Mise aux normes',
          'Accompagnement projet',
        ],
        pricing: 'Sur devis',
        popular: true,
        href: '/services/conseil',
        showQuoteForm: true,
        isPromoted: true,
        sortOrder: 1,
        createdBy: '1',
      },
      {
        name: 'Formation Professionnelle',
        slug: 'formation',
        shortDescription: "Formations techniques pour les professionnels de l'électricité",
        type: 'primary' as const,
        category: 'formation' as const,
        status: 'active' as const,
        icon: 'academic-cap',
        color: '#10B981',
        features: [
          'Formations certifiantes',
          'Instructeurs experts',
          'Matériel professionnel',
          'Suivi personnalisé',
          'Certification reconnue',
        ],
        pricing: 'À partir de 75 000 FCFA',
        popular: true,
        href: '/services/formation',
        showBookingForm: true,
        isPromoted: true,
        sortOrder: 2,
        createdBy: '1',
      },
      {
        name: 'Installation et Maintenance',
        slug: 'installation',
        shortDescription: "Services d'installation et de maintenance électrique professionnels",
        type: 'primary' as const,
        category: 'installation' as const,
        status: 'active' as const,
        icon: 'wrench-screwdriver',
        color: '#F59E0B',
        features: [
          'Installation certifiée',
          'Maintenance préventive',
          'Intervention 24h/24',
          'Garantie étendue',
          'Équipe qualifiée',
        ],
        pricing: 'Sur devis selon projet',
        popular: true,
        href: '/services/installation',
        showQuoteForm: true,
        isPromoted: true,
        sortOrder: 3,
        createdBy: '1',
      },
      {
        name: 'Livraison et Logistique',
        slug: 'livraison',
        shortDescription: 'Service de livraison rapide et fiable pour vos équipements électriques',
        type: 'primary' as const,
        category: 'livraison' as const,
        status: 'active' as const,
        icon: 'truck',
        color: '#8B5CF6',
        features: [
          'Livraison express',
          'Suivi temps réel',
          'Livraison sécurisée',
          'Retrait en magasin',
          'Emballage professionnel',
        ],
        pricing: 'À partir de 5 000 FCFA',
        popular: false,
        href: '/services/livraison',
        showQuoteForm: false,
        isPromoted: false,
        sortOrder: 4,
        createdBy: '1',
      },
      {
        name: 'Audit Énergétique',
        slug: 'audit-energetique',
        shortDescription:
          'Analyse complète de votre consommation énergétique pour optimiser vos coûts',
        type: 'complementary' as const,
        category: 'audit' as const,
        status: 'active' as const,
        icon: 'chart-bar',
        color: '#06B6D4',
        features: [
          'Mesures de consommation',
          'Analyse des pertes',
          "Recommandations d'amélioration",
          'ROI des investissements',
          'Suivi des économies',
        ],
        pricing: 'À partir de 200 000 FCFA',
        popular: true,
        href: '/services/audit-energetique',
        showQuoteForm: true,
        isPromoted: false,
        sortOrder: 5,
        createdBy: '1',
      },
    ]

    await Service.updateOrCreateMany('slug', services)
  }
}
